export const ROUTES = {
  HOME: '/',
  PROJECTS: '/projects',
  PROJECT_DETAIL: '/projects/:projectId',
  PROJECT_DETAIL_BUILD: (id: string) => `/projects/${id}`,
  EXPERIENCE: '/experience',
  EDUCATION: '/education',
  SKILLS: '/skills',
  CERTIFICATIONS: '/certifications',
  JD_MATCH: '/jd-match',
  CONTACT: '/contact',
  
  ADMIN_LOGIN: '/admin/login',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_PROFILE: '/admin/profile',
  ADMIN_SETTINGS: '/admin/settings',
  ADMIN_PROJECTS: '/admin/projects',
  ADMIN_EXPERIENCE: '/admin/experience',
  ADMIN_EDUCATION: '/admin/education',
  ADMIN_CERTIFICATIONS: '/admin/certifications',
  ADMIN_SKILLS: '/admin/skills',
  ADMIN_JD_QUERIES: '/admin/jd-queries',
  ADMIN_CONTACT_LEADS: '/admin/contact-leads',
} as const;
