# Common constants

CORRELATION_ID_HEADER = "X-Correlation-ID"

class ErrorCodes:
    VALIDATION_ERROR = "VALIDATION_ERROR"
    AUTH_ERROR = "AUTHENTICATION_ERROR"
    AUTHORIZATION_ERROR = "AUTHORIZATION_ERROR"
    NOT_FOUND = "NOT_FOUND"
    DUPLICATE_RECORD = "DUPLICATE_RECORD"
    DATABASE_ERROR = "DATABASE_ERROR"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"

class Messages:
    SUCCESS = "Success"
    VALIDATION_FAILED = "Validation failed"
    INTERNAL_ERROR = "An unexpected error occurred"
